import local from "next/font/local";
import "@/assets/globals.scss";
import Providers from "../components/layout/providers";
const Yekan = local({
  src: "../assets/fonts/YekanBakh-Regular.ttf",
});

export const metadata = {
  title: "Erfan Hosseini Portfolio",
  description: "Generated by Erfan Hosseini",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body className={`${Yekan.className}  `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
